export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"
plugins=(extract git tmux nmap rsync)
source $ZSH/oh-my-zsh.sh
alias hadown=curl -d '{"version": "'$1'"}' http://hassio/homeassistant/update
alias haup=hassio homeassisant update
alias halog=hassio homeassisant logs
alias hastop=hassio homeassisant stop
alias hastart=hassio homeassisant start
alias harestart=hassio homeassisant restart
alias hacheck=hassio homeassisant check
alias supup=hassio supervisor update
alias suplog=hassio supervisor logs
alias supinfo=hassio supervisor info
alias supreload=hassio supervisor reload
alias hostup=hassio host update
alias hostshut=hassio host shutdown
alias hosthard=hassio host hardware
alias hostreboot=hassio host reboot
