---
name: Deploy

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  ci:
    permissions:
      actions: read
      contents: read
      packages: read
      security-events: write
    uses: hassio-addons/workflows/.github/workflows/app-ci.yaml@e0c532a7b0fb264b3ff0c718c2c0308a0c8c1390 # v4.0.0

  deploy:
    needs: ci
    permissions:
      contents: read
      packages: write
    uses: hassio-addons/workflows/.github/workflows/app-deploy.yaml@e0c532a7b0fb264b3ff0c718c2c0308a0c8c1390 # v4.0.0
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
