---
name: Deploy

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  ci:
    permissions:
      actions: read
      contents: read
      packages: read
      security-events: write
    uses: hassio-addons/workflows/.github/workflows/app-ci.yaml@c953d10f34dac22eb68c1cdedbbc4106a89bef88 # v3.0.1

  deploy:
    needs: ci
    permissions:
      contents: read
      packages: write
    uses: hassio-addons/workflows/.github/workflows/app-deploy.yaml@c953d10f34dac22eb68c1cdedbbc4106a89bef88 # v3.0.1
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
